name: dors-test
channels:
  - conda-forge
dependencies:
  # R
  - r-reticulate 
  - r-dbi 
  - r-dplyr 
  - r-devtools
  - r-dbplyr
  # Python
  - python=3.8
  - pip
  # Dask
  - dask
  # testing / CI
  - flake8
  - ipywidgets
  - pytest
  - pytest-asyncio
  - black >=20.8b1
  - pyyaml
  - pyarrow
  # dask dependencies
  - cloudpickle
  - toolz
  - cytoolz
  - numpy
  - partd
  - dask
  - pandas
  - dask-sql
  # distributed dependencies
  - click >=6.6
  - msgpack-python
  - psutil >=5.0
  - six
  - sortedcontainers !=2.0.0,!=2.0.1
  - tblib
  - tornado >=5
  - distributed
  - zict >=0.1.3
  # `event_loop_policy` change See https://github.com/dask/distributed/pull/4212
  - pytest-asyncio >=0.14.0
  - pytest-timeout
