name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.8"]

    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Setup Conda Environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest"
          python-version: ${{ matrix.python-version }}
          environment-file: ci/environment.yml
          activate-environment: dors-test
          auto-activate-base: false

      - name: Install reticulate from Source
        shell: bash -l {0}
        run: Rscript -e 'devtools::install_github("rstudio/reticulate")'

      - name: Run tests
        shell: bash -l {0}
        run: Rscript -e "rcmdcheck::rcmdcheck(args = '--no-manual', error_on = 'warning', check_dir = 'check')"

